version: "3.3"
services:
  api:
    build: src/api/
    ports:
      - "7000:5000"
    volumes:
      - ./src/api:/app        # debug
      - ./lists/:/app/lists   # persistent storage
    #restart: always  # constant checking might cause blocking IP address in AH API

  web:
    image: halverneus/static-file-server
    volumes:
      - ./src/web/static/:/web
    ports:
      - "7001:8080"
    restart: always

networks:
  default:
    driver: bridge
